### ISSUE TITLE
What's the policy as to how list instances should be declared?

### ISSUE THREAD

**Issue by leftaroundabout** [Quid2/flat#5]
[In `Instances.hs`](https://github.com/Quid2/flat/blob/59707953d2bcf63db03fbd318b82a568958e4ff8/src/Data/Flat/Instances.hs#L59), there is this comment:
```haskell
-- Do not provide this to 'force' users to declare instances of concrete list types
instance {-# OVERLAPPABLE #-} Flat a => Flat [a]
instance {-# OVERLAPPING #-} Flat [Char]
```
I'm confused by what this means. The instance _is_ given, and doesn't actually seem different from the specialised `String` one... is this comment obsolete, or should one always manually define a list instance for any particular type that's used?

**Comment by tittoassini** [comment]
Not my clearest comment, obviously :-)

It means that if you do not provide the generic list instance than people will get an error when their data types include some list and that might nudge them to define instances for [TheirOwnDataType]. rather than [a].

Doing that is verbose but in some cases give you significantly better encoding/decoding times.
